/**
 * loom client 生成器（client-gen.ts）单测：
 * - 对 gis 应用生成 → 与已提交的 examples/gis/src/loom.client.ts 逐字节比对
 *   （快照即产物：漂移即失败，CI 新鲜度门的本地等价物）；
 * - 确定性（两次生成字节相同）、无 .http() 工具的跳过注释、自定义 path、
 *   POST 工具、agent 联合类型、头部 AUTO-GENERATED 注释。
 */
import { existsSync, readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { join, resolve } from 'node:path'
import { describe, expect, it } from 'vitest'
import { generateClient, pascalAlias } from '../src/client-gen.js'
import { defineApp } from '../src/index.js'

const GIS_DIR = resolve(fileURLToPath(new URL('.', import.meta.url)), '..', '..', '..', 'examples', 'gis')
/** 集成前置：@loom-sdk/web 编译产物存在（loom.app.ts 经它解析）。 */
const sdkBuilt = existsSync(join(GIS_DIR, 'node_modules', '@loom-sdk', 'web', 'lib', 'index.js'))

describe.skipIf(!sdkBuilt)('generateClient：对 gis 应用生成的快照', () => {
  it('生成物与已提交的 src/loom.client.ts 逐字节一致（漂移 = 声明已变，需重新生成）', async () => {
    const app = (await import(join(GIS_DIR, 'loom.app.ts'))).default as ReturnType<typeof defineApp>
    const generated = generateClient(app)
    const committed = readFileSync(join(GIS_DIR, 'src', 'loom.client.ts'), 'utf8')
    expect(generated).toBe(committed)
  })

  it('确定性：同一声明两次生成字节相同（不含时间戳）', async () => {
    const app = (await import(join(GIS_DIR, 'loom.app.ts'))).default as ReturnType<typeof defineApp>
    expect(generateClient(app)).toBe(generateClient(app))
  })
})

describe('generateClient：合成应用', () => {
  function miniApp() {
    const app = defineApp('mini')
    app
      .tool('get_only')
      .input({ region: { type: 'string' } })
      .output({ type: 'object', properties: { ok: { type: 'boolean', required: true } } })
      .http('GET')
      .execute(async () => ({ ok: true }))
    app
      .tool('post_thing')
      .input({ title: { type: 'string', required: true }, items: { type: 'array', required: true, items: { type: 'string' } } })
      .output({ type: 'object', properties: { id: { type: 'string', required: true } } })
      .http('POST')
      .execute(async () => ({ id: 'x' }))
    app
      .tool('custom_path')
      .input({})
      .output({ type: 'object', properties: { v: { type: 'number', required: true } } })
      .http('GET', '/~loom/special/path')
      .execute(async () => ({ v: 1 }))
    app.tool('model_only_face').execute(async () => ({}))
    app.agent('worker-a', { persona: 'a' })
    app.agent('worker-b', { persona: 'b' })
    return app
  }

  const source = generateClient(miniApp())

  it('头部注释（AUTO-GENERATED + 应用名）与 import type', () => {
    expect(source.startsWith('/**\n * AUTO-GENERATED by \'loom client\' — 勿手改，运行 pnpm loom client 重新生成')).toBe(true)
    expect(source).toContain('应用 mini 的类型化客户端')
    expect(source).toContain("import type { InferToolArgs, InferToolOutput } from '@loom-sdk/web'")
  })

  it('GET 工具：query 序列化 + 类型别名（InferToolArgs / InferToolOutput）', () => {
    expect(source).toContain('async get_only(args: GetOnlyArgs = {}, init?: RequestInit): Promise<GetOnlyOutput>')
    expect(source).toContain('export type GetOnlyArgs = InferToolArgs<')
    expect(source).toContain('export type GetOnlyOutput = InferToolOutput<')
    expect(source).toContain('loomQuery(args as Record<string, unknown>)}')
    expect(source).toContain('/** GET /~loom/api/get_only */')
  })

  it('POST 工具：JSON body（required 入参无默认值）', () => {
    expect(source).toContain('async post_thing(args: PostThingArgs, init?: RequestInit): Promise<PostThingOutput>')
    expect(source).toContain("body: JSON.stringify(args),")
    expect(source).toContain("method: 'POST',")
  })

  it('自定义 path（落在 apiPrefix 下）走基址相对拼接', () => {
    expect(source).toContain('/** GET /~loom/special/path */')
    expect(source).toContain('`${loomBaseUrl}/special/path${loomQuery(args as Record<string, unknown>)}`')
  })

  it('未声明 .http() 的工具生成跳过注释', () => {
    expect(source).toContain('// model_only_face：未声明 .http()，跳过；在声明处加 .http(method) 后重新生成')
  })

  it('agent id 生成为字面量联合类型', () => {
    expect(source).toContain("export type LoomAgentId = 'worker-a' | 'worker-b'")
    expect(source).toContain('async createSession(agentId: LoomAgentId, init?: RequestInit)')
    expect(source).toContain('async *streamEvents(')
    expect(source).toContain('AsyncIterable<LoomClientEvent>')
  })

  it('baseUrl 选项写入默认基址', () => {
    expect(generateClient(miniApp(), { baseUrl: 'http://127.0.0.1:4621/~loom/' })).toContain(
      "let loomBaseUrl = 'http://127.0.0.1:4621/~loom'",
    )
  })
})

describe('pascalAlias', () => {
  it('snake → Pascal，非法段丢弃且确定性', () => {
    expect(pascalAlias('gis_query_land_types')).toBe('GisQueryLandTypes')
    expect(pascalAlias('simple')).toBe('Simple')
    expect(pascalAlias('9lives')).toBe('Tool9lives')
  })
})
