/**
 * AUTO-GENERATED by 'loom client' — 勿手改，运行 pnpm loom client 重新生成
 *
 * 应用 gis-platform 的类型化客户端（M4）：
 * - loomTools：声明了 .http() 的工具 → 类型化 fetch 封装（入参 InferToolArgs、
 *   返回 InferToolOutput，类型映射来自 @loom-sdk/web——同一份声明驱动运行时与客户端）；
 * - loomSessions：会话客户端（agent id 为字面量联合类型；createSession /
 *   sendMessage 类型化；streamEvents 返回投影事件流的 AsyncIterable）。
 */
import type { InferToolArgs, InferToolOutput } from '@loom-sdk/web'

/** API 基址：浏览器缺省走同源代理（如 Vite 的 /~loom → 127.0.0.1:4620）；Node/测试可用 configureLoomClient 覆盖。 */
let loomBaseUrl = '/~loom'

/** 默认请求头（M7：app.auth 声明后放身份——token 或 x-loom-user；SSE 的 fetch 也带）。 */
let loomDefaultHeaders: Record<string, string> = {}

/** 覆盖基址（如 http://127.0.0.1:4620/~loom）与默认请求头。 */
export function configureLoomClient(opts: { baseUrl: string; headers?: Record<string, string> }): void {
  loomBaseUrl = opts.baseUrl.replace(/\/+$/, '')
  if (opts.headers !== undefined) loomDefaultHeaders = opts.headers
}

/** 投影事件（SSE 白名单载荷；seq 是唯一顺序权威）。 */
export interface LoomClientEvent {
  seq?: number
  type: string
  [key: string]: unknown
}

async function loomFetch<T>(url: string, init?: RequestInit): Promise<T> {
  const res = await fetch(url, { ...init, headers: { ...loomDefaultHeaders, ...(init?.headers as Record<string, string> | undefined) } })
  const body = (await res.json().catch(() => ({}))) as T & { error?: string }
  if (!res.ok) throw new Error(body.error ?? `loom client: ${res.status} ${res.statusText} ${url}`)
  return body
}

/** query 序列化：标量原样、数组/对象 JSON 化（与服务端 parseScalar 对称解析）。 */
function loomQuery(args: Record<string, unknown>): string {
  const params = new URLSearchParams()
  for (const [key, value] of Object.entries(args)) {
    if (value === undefined) continue
    params.set(key, typeof value === 'string' ? value : JSON.stringify(value))
  }
  const text = params.toString()
  return text === '' ? '' : `?${text}`
}

// ————————————————————————————————————————————————
// 工具客户端（.http() 第二张面孔的类型化封装）
// ————————————————————————————————————————————————

/** gis_query_land_types 的入参（由 .input() DSL 经 InferToolArgs 推导）。 */
export type GisQueryLandTypesArgs = InferToolArgs<{
    region: {
      type: "string",
      description: "可选的村庄名过滤词，如\"连河村\"；省略则返回全部 8 个村庄。",
    },
  }>

/** gis_query_land_types 的返回（由 .output() DSL 经 InferToolOutput 推导）。 */
export type GisQueryLandTypesOutput = InferToolOutput<{
    type: "object",
    properties: {
      totalAreaSqm: {
        type: "number",
        required: true,
      },
      items: {
        type: "array",
        items: {
          type: "object",
          properties: {
            village: {
              type: "string",
              required: true,
            },
            landType: {
              type: "string",
              required: true,
            },
            areaSqm: {
              type: "number",
              required: true,
            },
            ratioPct: {
              type: "number",
              required: true,
            },
          },
        },
        required: true,
      },
      queriedAt: {
        type: "string",
        required: true,
      },
    },
  }>

/** 各工具的调用端（服务端形状变化后重新生成，编译期即可发现调用点破坏）。 */
export const loomTools = {
  /** GET /~loom/api/gis_query_land_types */
  async gis_query_land_types(args: GisQueryLandTypesArgs = {}, init?: RequestInit): Promise<GisQueryLandTypesOutput> {
    return loomFetch<GisQueryLandTypesOutput>(`${loomBaseUrl}/api/gis_query_land_types${loomQuery(args as Record<string, unknown>)}`, { ...init, method: 'GET' })
  },
  // gis_render_pie_chart：未声明 .http()，跳过；在声明处加 .http(method) 后重新生成
  // gis_focus_map：未声明 .http()，跳过；在声明处加 .http(method) 后重新生成
  // gis_write_report：未声明 .http()，跳过；在声明处加 .http(method) 后重新生成
  // gis_update_land_note：未声明 .http()，跳过；在声明处加 .http(method) 后重新生成
}

// ————————————————————————————————————————————————
// 会话客户端（agent id 为字面量联合类型）
// ————————————————————————————————————————————————

/** 应用声明的智能体 id（字面量联合——传错 id 编译期即报）。 */
export type LoomAgentId = 'data-analysis' | 'data-governance' | 'report-writing'

/** 会话操作（创建 / 发消息 / 事件流）。 */
export const loomSessions = {
  /** POST /agents/:agentId/sessions → { sessionId } */
  async createSession(agentId: LoomAgentId, init?: RequestInit): Promise<{ sessionId: string; agentId: string }> {
    return loomFetch(`${loomBaseUrl}/agents/${encodeURIComponent(agentId)}/sessions`, { ...init, method: 'POST' })
  },

  /** POST /agents/:agentId/sessions/:sessionId/messages（进度走 streamEvents）。 */
  async sendMessage(
    agentId: LoomAgentId,
    sessionId: string,
    text: string,
    init?: RequestInit,
  ): Promise<{ ok: true; sessionId: string }> {
    return loomFetch(`${loomBaseUrl}/agents/${encodeURIComponent(agentId)}/sessions/${encodeURIComponent(sessionId)}/messages`, {
      ...init,
      method: 'POST',
      headers: { 'content-type': 'application/json', ...(init?.headers as Record<string, string> | undefined) },
      body: JSON.stringify({ text }),
    })
  },

  /** GET …/events?since=N —— 投影事件流（SSE）的 AsyncIterable；for await...of 消费，abort 即拆除连接。 */
  async *streamEvents(
    agentId: LoomAgentId,
    sessionId: string,
    opts: { since?: number; signal?: AbortSignal } = {},
  ): AsyncIterable<LoomClientEvent> {
    const since = opts.since ?? -1
    const url = `${loomBaseUrl}/agents/${encodeURIComponent(agentId)}/sessions/${encodeURIComponent(sessionId)}/events?since=${since}`
    const res = await fetch(url, { signal: opts.signal, headers: { accept: 'text/event-stream', ...loomDefaultHeaders } })
    if (!res.ok || res.body === null) throw new Error(`loom client: SSE 打开失败 ${res.status} ${url}`)
    const reader = res.body.getReader()
    const decoder = new TextDecoder()
    let buffer = ''
    try {
      for (;;) {
        const { done, value } = await reader.read()
        if (done) break
        buffer += decoder.decode(value, { stream: true })
        let index: number
        while ((index = buffer.indexOf('\n\n')) >= 0) {
          const block = buffer.slice(0, index)
          buffer = buffer.slice(index + 2)
          for (const line of block.split('\n')) {
            if (!line.startsWith('data: ')) continue
            try {
              yield JSON.parse(line.slice(6)) as LoomClientEvent
            } catch { /* 非 JSON 行（心跳注释等）忽略 */ }
          }
        }
      }
    } finally {
      await reader.cancel().catch(() => undefined)
    }
  },
}
