/**
 * AUTO-GENERATED by 'loom import-openapi' — 勿手改；源头文档变更后重新生成。
 *
 * OpenAPI 3.0.3 → 5 个 Loom 工具
 *
 * 接入：在 loom.app.ts 里 import { registerImportedTools } from './<本文件名>'，
 * 然后一行 registerImportedTools(app)——外部 API 即获得模型面孔 + HTTP 面孔，
 * 策略/审批/投影照常生效（写操作声明处有 approve 建议）。
 * 降级说明：源头 schema 里 Loom DSL 不覆盖的部分已诚实降级，见各处 WARN(openapi-import) 注释。
 */
import type { App } from '@loom-sdk/web'

/** API 基址 （--base 覆盖）。 */
let loomImportBase = "http://127.0.0.1:4710"

/** 覆盖基址（如指向本地代理 / 测试实例）。 */
export function configureImportedClient(opts: { baseUrl: string }): void {
  loomImportBase = opts.baseUrl.replace(/\/+$/, '')
}

// 源头声明了 securitySchemes：token 缺省读 LOOM_IMPORT_TOKEN 环境变量。
// TODO: 按需注入认证头（bearer → Authorization；apiKey 按声明位置）
const token = process.env.LOOM_IMPORT_TOKEN

/** 认证头（bearer → Authorization；apiKey 按声明的 header 名注入）。 */
function authHeaders(token: string): Record<string, string> {
  return {
    "X-Api-Key": `${token}`,
  }
}

/** 从 args 里挑出指定字段（undefined 跳过；requestBody 组装用）。 */
function pick(args: Record<string, unknown>, keys: readonly string[]): Record<string, unknown> {
  const out: Record<string, unknown> = {}
  for (const key of keys) {
    const value = args[key]
    if (value !== undefined) out[key] = value
  }
  return out
}

/** query 值编码：标量原样，复杂值 JSON 编码（与服务端 parseScalar 对称）。 */
function encodeQueryValue(value: unknown): string {
  return typeof value === 'string' ? value : JSON.stringify(value)
}

export function registerImportedTools(app: App): void {
  app
    .tool("erp_list_products")
    .description("商品清单（含库存）\n\n返回全部商品：编号、名称、规格、单位、单价、当前库存与最后库存变更时间。支持按名称关键字过滤。\n\n来源标签：products\n\n导入自 OpenAPI 文档：GET /api/products")
    .input({ keyword: { type: "string", description: "商品名称过滤词（部分匹配），如\"轴承\"" } })
    .output({
      type: "array",
      items: {
        type: "object",
        properties: {
          id: { type: "string", description: "商品编号，如 P101", required: true },
          name: { type: "string", description: "商品名称，如\"轴承 D60\"", required: true },
          spec: { type: "string", description: "规格", required: true },
          unit: { type: "string", description: "计价单位，如 个/桶/条", required: true },
          price: { type: "number", description: "单价（元）", required: true },
          stock: { type: "integer", description: "当前库存", required: true },
          updatedAt: { type: "string", description: "最后库存变更时间（ISO 8601）", required: true },
        },
      },
    })
    .http("GET")
    .execute(async (args, exec) => {
    const path = `/api/products`
    const query = new URLSearchParams()
    if (args["keyword"] !== undefined) query.set("keyword", encodeQueryValue(args["keyword"]))
    const qs = query.toString()
    const url = `${loomImportBase}${path}${qs === "" ? "" : `?${qs}`}`
    const res = await fetch(url, {
      method: "GET",
      signal: exec.signal,
      headers: { ...(token === undefined ? {} : authHeaders(token)) },
    })
    if (!res.ok) {
      const text = await res.text().catch(() => '')
      throw new Error(`erp_list_products 调用失败：HTTP ${res.status}——${text.slice(0, 200)}`)
    }
    return await res.json()
    })
  app
    .tool("erp_get_product")
    .description("查单个商品\n\n按商品编号查详情（当年没写响应 schema，返回字段与清单一致）。\n\n来源标签：products\n\n导入自 OpenAPI 文档：GET /api/products/{id}")
    .input({
      id: { type: "string", required: true, description: "商品编号，如 P101；原路径参数（GET /api/products/{id} 的 {id}）" },
    })
    // WARN(openapi-import): output——erp_get_product 的成功响应缺少 application/json schema，输出按任意 JSON 处理
    .output({ type: "json" })
    .http("GET")
    .execute(async (args, exec) => {
    const path = `/api/products/${encodeURIComponent(String(args["id"] ?? ''))}`
    const url = `${loomImportBase}${path}`
    const res = await fetch(url, {
      method: "GET",
      signal: exec.signal,
      headers: { ...(token === undefined ? {} : authHeaders(token)) },
    })
    if (!res.ok) {
      const text = await res.text().catch(() => '')
      throw new Error(`erp_get_product 调用失败：HTTP ${res.status}——${text.slice(0, 200)}`)
    }
    // 输出已降级为任意 JSON（见上方 WARN）：结果原样返回
    return await res.json()
    })
  app
    .tool("erp_list_customers")
    .description("客户清单\n\n来源标签：customers\n\n导入自 OpenAPI 文档：GET /api/customers")
    .input({})
    .output({
      type: "array",
      items: {
        type: "object",
        properties: {
          id: { type: "string", description: "客户编号，如 C001", required: true },
          name: { type: "string", description: "联系人", required: true },
          company: { type: "string", description: "单位名称", required: true },
          phone: { type: "string", description: "联系电话", required: true },
          city: { type: "string", description: "城市", required: true },
          creditLevel: { type: "string", description: "信用等级（A/B/C）", required: true },
        },
      },
    })
    .http("GET")
    .execute(async (args, exec) => {
    const path = `/api/customers`
    const url = `${loomImportBase}${path}`
    const res = await fetch(url, {
      method: "GET",
      signal: exec.signal,
      headers: { ...(token === undefined ? {} : authHeaders(token)) },
    })
    if (!res.ok) {
      const text = await res.text().catch(() => '')
      throw new Error(`erp_list_customers 调用失败：HTTP ${res.status}——${text.slice(0, 200)}`)
    }
    return await res.json()
    })
  app
    .tool("erp_get_customer")
    .description("查单个客户\n\n来源标签：customers\n\n导入自 OpenAPI 文档：GET /api/customers/{id}")
    .input({
      id: { type: "string", required: true, description: "客户编号，如 C001；原路径参数（GET /api/customers/{id} 的 {id}）" },
    })
    .output({
      type: "object",
      properties: {
        id: { type: "string", description: "客户编号，如 C001", required: true },
        name: { type: "string", description: "联系人", required: true },
        company: { type: "string", description: "单位名称", required: true },
        phone: { type: "string", description: "联系电话", required: true },
        city: { type: "string", description: "城市", required: true },
        creditLevel: { type: "string", description: "信用等级（A/B/C）", required: true },
      },
    })
    .http("GET")
    .execute(async (args, exec) => {
    const path = `/api/customers/${encodeURIComponent(String(args["id"] ?? ''))}`
    const url = `${loomImportBase}${path}`
    const res = await fetch(url, {
      method: "GET",
      signal: exec.signal,
      headers: { ...(token === undefined ? {} : authHeaders(token)) },
    })
    if (!res.ok) {
      const text = await res.text().catch(() => '')
      throw new Error(`erp_get_customer 调用失败：HTTP ${res.status}——${text.slice(0, 200)}`)
    }
    return await res.json()
    })
  app
    .tool("erp_orders_create")
    .description("创建销售订单（写操作：扣库存）\n\n创建订单并立即扣减库存。请求体：customerId 是客户编号（如 C001）；items 是购买明细数组，每项 {productId, qty}（商品编号与数量）。库存不足返回 409，订单不落账。\n\n来源标签：orders\n\n导入自 OpenAPI 文档：POST /api/orders")
    // WARN(openapi-import): input.body.customerId——约束 minLength=1 不在 DSL 覆盖内，已丢弃（保留类型）
    // WARN(openapi-import): input.body.items——约束 minItems=1 不在 DSL 覆盖内，已丢弃（保留类型）
    .input({ customerId: { type: "string", required: true }, items: { type: "array", required: true } })
    .output({
      type: "object",
      properties: {
        orderId: { type: "string", description: "订单号，如 SO-2026-0819-003", required: true },
        customerId: { type: "string", description: "客户编号", required: true },
        items: {
          type: "array",
          items: {
            type: "object",
            properties: {
              productId: { type: "string", description: "商品编号", required: true },
              productName: { type: "string", description: "商品名称", required: true },
              qty: { type: "integer", description: "数量", required: true },
              unitPrice: { type: "number", description: "成交单价", required: true },
            },
          },
          description: "明细",
          required: true,
        },
        totalAmount: { type: "number", description: "订单总额", required: true },
        createdAt: { type: "string", description: "创建时间（ISO 8601）", required: true },
      },
    })
    // 建议：app.policy 中为该写操作配置 approve（POST /api/orders——真实写操作应走人工审批）
    .http("POST")
    .execute(async (args, exec) => {
    const path = `/api/orders`
    const url = `${loomImportBase}${path}`
    const payload = pick(args, ["customerId","items"])
    const res = await fetch(url, {
      method: "POST",
      signal: exec.signal,
      headers: { 'content-type': 'application/json', ...(token === undefined ? {} : authHeaders(token)) },
      body: JSON.stringify(payload),
    })
    if (!res.ok) {
      const text = await res.text().catch(() => '')
      throw new Error(`erp_orders_create 调用失败：HTTP ${res.status}——${text.slice(0, 200)}`)
    }
    return await res.json()
    })
}
